name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}/__service__
      - uses: int128/docker-build-cache-config-action@v1
        id: cache
        with:
          image: ghcr.io/${{ github.repository }}/cache
          flavor: prefix=__service__--
      - uses: docker/setup-buildx-action@v3
      - uses: docker/bake-action@v5
        id: bake
        with:
          push: true
          files: |
            ./docker-bake.hcl
            ${{ steps.metadata.outputs.bake-file }}
            ${{ steps.cache.outputs.bake-file }}
      - uses: actions/github-script@v7
        env:
          bake_metadata: ${{ steps.bake.outputs.metadata }}
        with:
          script: |
            const metadata = JSON.parse(process.env.bake_metadata)
            const services = Object.keys(metadata)
            for (const service of services) {
              const digest = metadata[service]['containerimage.digest']
              const image = metadata[service]['image.name']
              const uri = `${image}@${digest}`
              core.info(`${service}=${uri}`)
            }
      - run: kustomize build
