name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}/__service__
      - uses: int128/docker-build-cache-config-action@v1
        id: cache
        with:
          image: ghcr.io/${{ github.repository }}/cache
          flavor: prefix=__service__--
      - uses: docker/setup-buildx-action@v3
      - uses: docker/bake-action@v5
        id: bake
        with:
          push: true
          files: |
            ./docker-bake.hcl
            ${{ steps.metadata.outputs.bake-file }}
            ${{ steps.cache.outputs.bake-file }}
      - run: jq . <<< "$BAKE_METADATA"
        env:
          BAKE_METADATA: ${{ steps.bake.outputs.metadata }}
